version: '3'

services:
  db:
    image: nouchka/sqlite3:latest

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: weChat
    ports:
      - 8000:8000
    depends_on:
      - db
